name = "S2MPJ"
uuid = "fd94f3da-1170-49fe-b64d-eb23ffeac5f0"
authors = []
version = "1.0.0-DEV"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
SparseArrays = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
